# Generated by Django 5.0.6 on 2026-08-11 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('icon', models.CharField(default='check', max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('icon', models.CharField(default='building', help_text="Icon key the frontend maps to a line-icon component, e.g. 'building', 'land', 'villa', 'condo'.", max_length=40)),
                ('description', models.CharField(blank=True, max_length=280)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('badge_label', models.CharField(blank=True, help_text="e.g. 'PREMIUM SELECTION' shown on the featured category card.", max_length=40)),
                ('is_specific_need', models.BooleanField(default=False, help_text="True for the 4 small 'Specific Needs' cards (Apartments, Office Space, Villas, Condos).")),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('purchase_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('lease', 'Lease / Hire')], default='sale', max_length=10)),
                ('property_type', models.CharField(choices=[('detached', 'Detached House'), ('semi_detached', 'Semi-Detached'), ('apartment', 'Luxury Apartment'), ('villa', 'Villa'), ('condo', 'Condo'), ('land', 'Land'), ('office', 'Office Space'), ('warehouse', 'Warehouse'), ('event_center', 'Event Center')], default='detached', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rent_period', models.CharField(blank=True, choices=[('night', '/night'), ('day', '/day'), ('year', '/yr'), ('month', '/mo')], help_text='Only used when purchase_type is rent or lease, e.g. /night, /yr, /day.', max_length=10)),
                ('area', models.CharField(help_text='e.g. Ikoyi, Victoria Island, Maitama', max_length=80)),
                ('city', models.CharField(help_text='e.g. Lagos, Abuja', max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('full_address', models.CharField(blank=True, max_length=220)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('size_sqm', models.PositiveIntegerField(blank=True, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('summary', models.CharField(blank=True, help_text='Short description shown on cards.', max_length=280)),
                ('description', models.TextField(blank=True, help_text="Full 'Property Overview' body copy, paragraphs.")),
                ('is_top_choice', models.BooleanField(default=False, help_text="Shows the green 'TOP CHOICE' ribbon badge.")),
                ('is_featured', models.BooleanField(default=False, help_text="Shown in the homepage 'Featured Property' grid.")),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='properties.amenity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.category')),
                ('listed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='team.teammember')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
