# Generated by Django 5.0.6 on 2026-08-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='Dev-mode fallback: an external image URL used when no file is uploaded to hero_image.'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Dev-mode fallback: an external image URL used when no file is uploaded to image.'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
