# Generated by Django 5.0.6 on 2026-08-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('title', models.CharField(help_text='e.g. Senior Consultant, Principal Partner', max_length=120)),
                ('specialty_tag', models.CharField(help_text='e.g. COMMERCIAL, RESIDENTIAL, PORTFOLIO MGT', max_length=40)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True, help_text='Optional short bio for an inline expand — no dedicated page.')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
