# Generated by Django 5.0.6 on 2026-08-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Dev-mode fallback: an external image URL used when no file is uploaded to photo.'),
        ),
    ]
